### ISSUE TITLE
Rename appearsIn

### ISSUE THREAD

**Issue by aidhog** [scferrada/imgpedia#2]
We should rename appearsIn in the next version since the name is a bit misleading:

IMG appearsIn RESOURCE .

... better something like "associatedWith".

**Comment by scferrada** [comment]
I believe we should have two relations. `appearsIn` linking to the Wikipedia article and `associatedWith` for the links to DBpedia. Would that be reasonable?

**Comment by aidhog** [comment]
Yep, sounds good!

**Comment by scferrada** [comment]
It's all updated and online.
