### ISSUE TITLE
Image downloading link seems to be out of date.

### ISSUE THREAD

**Issue by kleinercubs** [scferrada/imgpedia#5]
Hi. I think Imgpedia is an outstanding work and I want to follow this work. However, I found those downloading link seems to be unaccessable. Could you please update the link that could directly downloading the whole dataset?

**Comment by scferrada** [comment]
Hi, sorry for the late response. Indeed the URL http://imgpedia.dcc.uchile.cl/dumps is not working. I'm contacting the Sysadmin of my previous university to get it fixed ASAP.

Note, however, that we do not provide a direct means to download the images of Wikimedia, but rather our RDF files. To get the images, I can refer you to: https://meta.wikimedia.org/wiki/Mirroring_Wikimedia_project_XML_dumps#Media

Cheers and thanks for your interest on IMGpedia.

**Comment by scferrada** [comment]
Hi,

The URL with the dumps is now live. Please let me know if there's anything I can help you with.

Cheers.
