### ISSUE TITLE
 slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by chzaryab** [scferrada/imgpedia#7]
my code:
computer = ColorLayoutComputer()
#so descriptor is a vector of 2 x 2 x 32 dimensions
img = cv2.imread("input/image-for-convolution-kernal/1.jpg")
descriptor = computer.compute(img) #so descriptor is a vector of 2 x 2 x 32 dimensions

Error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_17/3661175869.py in <module>
      2 #so descriptor is a vector of 2 x 2 x 32 dimensions
      3 img = cv2.imread("input/image-for-convolution-kernal/1.jpg")
----> 4 descriptor = computer.compute(img) #so descriptor is a vector of 2 x 2 x 32 dimensions

/tmp/ipykernel_17/2407321064.py in compute(self, img)
     15                 for row in range(self.rows):
     16                         for col in range(self.cols):
---> 17                                 slice = img[imgH/self.rows * row: imgH/self.rows * (row+1), imgW/self.cols*col : imgW/self.cols*(col+1)]
     18                                 average_color_per_row = np.mean(slice, axis=0)
     19                                 average_color = np.mean(average_color_per_row, axis=0)

TypeError: slice indices must be integers or None or have an __index__ method

**Comment by chzaryab** [comment]
slice = img[int(imgH/self.rows * row): int(imgH/self.rows * (row+1)), int(imgW/self.cols*col) : int(imgW/self.cols*(col+1))]
change this in the code and it will work

**Comment by scferrada** [comment]
Thanks for opening this issue. These descriptors were implemented with Python 2, where division of integers returned integers, which has changed for Python 3. I will add the change that you suggest.
